config/routes.rb
Rails.application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'home#letsencrypt'

  root to: "home#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :events do
    get 'deleted' => "events#deleted", on: :collection
    get 'past' => "events#past", on: :collection
    get 'future' => "events#future", on: :collection
    match 'recover', to: 'events#recover', on: :member, via: [:put, :patch]
  end

  resources :companies do
    get 'deleted' => 'companies#deleted', on: :collection
    match 'recover', to: 'companies#recover', on: :member, via: [:put, :patch]
  end

  resources :programs do
    resources :seasons do
      get 'deleted' => 'seasons#deleted', on: :collection
      match 'recover', to: 'seasons#recover', on: :member, via: [:put, :patch]
    end
    get 'deleted' => 'programs#deleted', on: :collection
    match 'recover', to: 'programs#recover', on: :member, via: [:put, :patch]
  end

  resources :projects do
    get 'deleted' => 'projects#deleted', on: :collection
    match 'recover', to: 'projects#recover', on: :member, via: [:put, :patch]
    resources :members, only: [:create], controller: :project_members
    resources :logs, only: [:index, :create, :destroy], controller: :logs
  end

  resources :roles, only: [:destroy]

  resources :floors do
    get 'deleted' => 'floors#deleted', on: :collection
    match 'recover', to: 'floors#recover', on: :member, via: [:put, :patch]
  end

  resources :meeting_rooms do
    get 'deleted' => 'meeting_rooms#deleted', on: :collection
    match 'recover', to: 'meeting_rooms#recover', on: :member, via: [:put, :patch]
  end

  resources :reservations, except: [:show] do
    get 'past' => "reservations#past", on: :collection
    get 'deleted' => "reservations#deleted", on: :collection
    match 'recover', to: 'reservations#recover', on: :member, via: [:put, :patch]
    get 'search' => "reservations#search", on: :collection
  end

  resources :residents, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  namespace :api, defaults: {format: :json} do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      scope :events do
        get '/' => 'events#index'
        get 'today' => 'events#today'
        get 'public' => 'events#public'
      end
      scope :residents do
        get '/' => 'residents#index'
        get 'last' => 'residents#last'
      end
      scope :companies do
        get '/' => 'companies#index'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting_room.rb
class MeetingRoom < ApplicationRecord
  belongs_to :floor
  has_many :reservations, dependent: :destroy

  acts_as_paranoid
  audited

  def reservation_at(start_time, end_time)
    reservations = []
    self.reservations.each do |reservation|
      if start_time != reservation.end_time && end_time != reservation.start_time
        if start_time.between?(reservation.start_time, reservation.end_time)
          reservations.push reservation
        elsif end_time.between?(reservation.start_time, reservation.end_time)
          reservations.push reservation
        elsif reservation.start_time.between?(start_time, end_time)
          reservations.push reservation
        elsif reservation.end_time.between?(start_time, end_time)
          reservations.push reservation
        end
      end
    end
    if reservations.length > 0
      return reservations
    else
      return false
    end
  end

  def is_available
    if self.status.blank?
      return true
    else
      return false
    end
  end

  def colour
    self.floor.colour.present? ? self.floor.colour : ""
  end

end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  before_action :set_meeting_room, only: [:show, :edit, :update, :destroy, :recover]
  load_and_authorize_resource

  # GET /meeting_rooms
  # GET /meeting_rooms.json
  def index
    @meeting_rooms = MeetingRoom.all.order('floor_id ASC')
  end

  # GET /meeting_rooms/deleted
  def deleted
    @meeting_rooms = MeetingRoom.only_deleted
  end

  # GET /meeting_rooms/1
  # GET /meeting_rooms/1.json
  def show
  end

  # GET /meeting_rooms/new
  def new
    @meeting_room = MeetingRoom.new
  end

  # GET /meeting_rooms/1/edit
  def edit
  end

  # POST /meeting_rooms
  # POST /meeting_rooms.json
  def create
    @meeting_room = MeetingRoom.new(meeting_room_params)

    respond_to do |format|
      if @meeting_room.save
        format.html { redirect_to meeting_rooms_url, notice: I18n.t('meeting_rooms.create') }
        format.json { render :show, status: :created, location: @meeting_room }
      else
        format.html { render :new }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meeting_rooms/1
  # PATCH/PUT /meeting_rooms/1.json
  def update
    respond_to do |format|
      if @meeting_room.update(meeting_room_params)
        format.html { redirect_to meeting_rooms_url, notice: I18n.t('meeting_rooms.update') }
        format.json { render :show, status: :ok, location: @meeting_room }
      else
        format.html { render :edit }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /meeting_rooms/1/recover
  def recover
    @meeting_room.recover
    respond_to do |format|
      format.html { redirect_to meeting_rooms_url, notice: I18n.t('meeting_rooms.recover') }
      format.json { head :success }
    end
  end

  # DELETE /meeting_rooms/1
  # DELETE /meeting_rooms/1.json
  def destroy
    @meeting_room.destroy
    respond_to do |format|
      format.html { redirect_to meeting_rooms_url, notice: I18n.t('meeting_rooms.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting_room
      @meeting_room = MeetingRoom.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_room_params
      params.require(:meeting_room).permit(:name, :floor_id, :photo, :capacity, :reservable, :description, :status)
    end
end

app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper
end

app/views/meeting_rooms/_form.html.erb
<%= simple_form_for(@meeting_room) do |f| %>
  <%= f.error_notification %>

  <div class="col-xs-12">
    <h2 class="page__title">
      <% if f.object.new_record? %>
        <%= title "Ajouter un espace" %>
      <% else %>
        <%= title "Modifier un espace" %>
      <% end %>
    </h2>
  </div>

  <div class="col-xs-12 col-md-8">
    <div class="panel">
      <div class="panel-heading">
        <h3>Informations générales</h3>
      </div>
      <div class="panel-body">
        <div class="row form-row">

          <div class="form-group col-md-12">
            <%= f.label :name, "Nom de l'espace", class: "sr-only" %>
            <%= f.text_field :name, placeholder: "Nom de l'espace", class: "form-control" %>
          </div>

          <div class="form-group col-md-12">
            <%= f.label :description, "Description" %>
            <%= f.input_field :description, input_html: { rows: 3 }, class: "form-control" %>
          </div>

          <div class="form-group select-wrapper col-md-6 has-feedback has-feedback-left">
            <%= f.label :floor, "Étage", class: "sr-only" %>
            <%= f.association :floor, collection: Floor.order('number ASC'), class: 'form-control', label: false, prompt: "Étage" %>
            <i class="form-control-feedback material-icons">view_agenda</i>
          </div>

          <div class="form-group col-md-6 has-feedback has-feedback-left">
            <%= f.label :capacity, "Capacité de l'espace", class: "sr-only" %>
            <%= f.text_field :capacity, placeholder: "Capacité de l'espace", class: "form-control" %>
            <i class="form-control-feedback material-icons">people</i>
          </div>

        </div>
      </div>
  </div>
</div>

<div class="col-xs-12 col-md-4">
  <div class="panel">
    <div class="panel-heading">
      <h3>Publier</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.input :reservable, inline_label: "Espace reservable", as: :boolean %>
        <p class="muted">Signifie que cet espace sera disponible à la reservation sur l'admin.</p>

        <div class="checkbox">
          <label>
            <% if meeting_room.is_available %>
              <input type="checkbox" class="helper-toggle">
            <% else %>
              <input type="checkbox" checked="checked" class="helper-toggle">
            <% end %>
            Rendre cet espace provisoirement indisponible
          </label>
        </div>
        <div class="row">
          <% if meeting_room.is_available %>
            <div class="form-group toggle-group hidden col-md-12 has-feedback has-feedback-left">
          <% else %>
            <div class="form-group toggle-group col-md-12 has-feedback has-feedback-left">
          <% end %>
            <%= f.label :status, "Raison", class: "sr-only" %>
            <%= f.text_field :status, placeholder: "Raison", class: "form-control toggle-form-control" %>
            <i class="form-control-feedback material-icons">help</i>
          </div>
        </div>
      </div>
      <ul class="simple-list muted">
        <% if @meeting_room.created_at.present? %>
          <li>
            <% if @meeting_room.audits.present? %>
              <% user_id = @meeting_room.audits.first.user.id %>
              <%= 'Créé il y a ' + time_ago_in_words(@meeting_room.created_at) + ' par ' %>
              <%= link_to @meeting_room.audits.first.user.name, resident_path(user_id) %>.
            <% else %>
              <%= 'Créé il y a ' + time_ago_in_words(@meeting_room.created_at) + '.' %>
            <% end %>
          </li>
        <% end %>
        <% if @meeting_room.updated_at != @meeting_room.created_at %>
          <li>
            <% if @meeting_room.audits.present? %>
            <%-# Évènement créés avec Audited -%>
              <% user_id = @meeting_room.audits.last.user.id %>
              <%= 'Modifié il y a ' + time_ago_in_words(@meeting_room.updated_at) + ' par ' %>
              <%= link_to @meeting_room.audits.last.user.name, resident_path(user_id) %>.
            <% else %>
            <%-# Évènement créés avant Audited -%>
              <%= 'Modifié il y a ' + time_ago_in_words(@meeting_room.updated_at) + '.' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="panel-footer">
      <% if f.object.new_record? %>
        <div class="flex-end">
          <%= f.submit "Publier", class: "btn btn-primary" %>
        </div>
      <% else %>
        <div class="space-between">
          <%= link_to 'Supprimer', meeting_room, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link btn-link--danger" %>
          <%= f.submit "Sauvegarder", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% end %>

app/views/meeting_rooms/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Étage</th>
      <th>Capacité</th>
      <th>Réservable</th>
      <th>Statut</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meeting_rooms.each do |meeting_room| %>
    <tr>
      <td>
        <div class="list-dot" style="background-color: <%= meeting_room.colour %>"></div>
        <%= meeting_room.name %>
      </td>
      <td><%= meeting_room.floor.present? ? meeting_room.floor.name : "N/A" %></td>
      <td><%= meeting_room.capacity %></td>
      <td><%= meeting_room.reservable? ? "Oui" : "Non" %></td>
      <td><%= meeting_room.is_available ? "Disponible" : meeting_room.status %></td>
      <td>
        <div class="pull-right">
          <% if current_page?(action: 'index') %>
            <%= link_to meeting_room, class: 'btn btn-default btn-xs' do %>
            <i class="material-icons">visibility</i><span>Voir les réservations</span>
            <% end %>
            <%= link_to edit_meeting_room_path(meeting_room), class: 'btn btn-default btn-xs' do %>
            <i class="material-icons">edit</i><span>Modifier</span>
            <% end %>
          <% end %>
          <% if current_page?(action: 'deleted') %>
            <%= link_to recover_meeting_room_path(meeting_room), method: :put, class: 'btn btn-success btn-xs' do %>
            <i class="material-icons">restore</i><span>Rétablir</span>
            <% end %>
          <% end %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/meeting_rooms/_room-item.html.erb
<!-- TODO: change reservation-infos to room -->
<% if type == "search" %>
  <% reservation_end_time = @search.start_time + @search.length.to_s.to_i %>
  <div class="room-item <%= reservations = room.reservation_at(@search.start_time, reservation_end_time) ? 'booked' : '' %>" style="background-color: <%= room.colour %>">
<%elsif type == "link" %>
  <div class="room-item" style="background-color: <%= room.colour %>">
<% else %>
  <div class="room-item booked" style="background-color: <%= room.colour %>">
<% end %>

  <div class="room-item__content">
    <div class="room-item__title"><%= room.name %></div>
    <div class="room-item__subtitle">
      <%= room.floor.present? ? room.floor.name : "N/A" %> - <%= room.capacity %> <%= 'place'.pluralize(room.capacity) %>
    </div>
  </div>

  <div class="room-item__bottom">
    <% if type == "search" %>

      <% if reservations = room.reservation_at(@search.start_time, reservation_end_time) %>

        <%-# Already booked -%>
        <% if reservations.count > 1 %>

          <%-# More than 1 reservation -%>
          <span class="btn room-item__btn">Réservé</span>

          <div class="room-item__dropdown">
            <% reservations.each do |reservation| %>
              <div class="room-item__infos">
                Réservé de <%= reservation.start_time.strftime('%Hh') + (reservation.start_time.strftime('%M') != '00' ? reservation.start_time.strftime('%M') : '') + ' à ' + reservation.end_time.strftime('%Hh') + (reservation.end_time.strftime('%M') != '00' ? reservation.end_time.strftime('%M') : '') %> par
              </div>

              <% if reservation.user == current_user %>
                <span class="room-info__resident">Vous (<%= link_to "Annuler", reservation, method: :delete %>)</span>
              <% else %>
                <%= link_to reservation.user.name, resident_path(reservation.user), class: 'room-info__resident' %>
              <% end %>
            <% end %>
          </div>

        <% else %>

          <%-# 1 reservation -%>
          <% reservations.each do |reservation| %>
            <div class="room-item__infos">
              Réservé de <%= reservation.start_time.strftime('%Hh') + (reservation.start_time.strftime('%M') != '00' ? reservation.start_time.strftime('%M') : '') + ' à ' + reservation.end_time.strftime('%Hh') + (reservation.end_time.strftime('%M') != '00' ? reservation.end_time.strftime('%M') : '') %>
              <%= reservation.user != current_user ? 'par' : ' ' %>
            </div>

            <% if reservation.user == current_user %>
              <%= link_to "Annuler", reservation, method: :delete, class: 'btn room-item__btn', style: 'color:' + room.colour + ';' %>
            <% else %>
              <%= link_to reservation.user.name, resident_path(reservation.user), class: 'room-info__resident' %>
            <% end %>
          <% end %>

        <% end %>

      <% else %>

        <%-# Not booked -%>
        <%= simple_form_for @reservation do |f| %>
          <%= f.input :meeting_room_id, as: :hidden, input_html: { value: room.id } %>
          <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
          <%= f.input :start_time, as: :hidden, input_html: { value: @search.start_time } %>
          <%= f.input :end_time, as: :hidden, input_html: { value: reservation_end_time } %>

          <% label = 'Réserver de ' + @search.start_time.strftime('%Hh') + (@search.start_time.strftime('%M') != '00' ? @search.start_time.strftime('%M') : '') + ' à ' + reservation_end_time.strftime('%Hh') + (reservation_end_time.strftime('%M') != '00' ? reservation_end_time.strftime('%M') : '') %>
          <%= f.submit label, class: 'btn room-item__btn', style: 'color:' + room.colour + ';' %>
        <% end %>

      <% end %>

    <% end %>

    <% if type == "link" %>

      <span class="btn room-item__btn">Voir les réservations</span>
      <div class="room-item__dropdown">
        <span class="room-info__resident">Cette fonctionnalité arrive bientôt !</span>
      </div>

    <% end %>

    <% if type == "reservation" %>

      <% if reservation.user == current_user && reservation.start_time > Time.current %>
        <%= link_to "Annuler", reservation, method: :delete, class: 'btn room-item__btn' %>
      <% elsif (reservation.start_time <= Time.current && reservation.end_time >= Time.current) %>
        <span class="btn room-item__btn" style="color:<%= room.colour %>;">En cours</span>
      <%else %>
        <span class="btn room-item__btn" style="color:<%= room.colour %>;">Terminée</span>
      <% end %>

    <% end %>
  </div>
</div>

app/views/meeting_rooms/deleted.html.erb
<h2 class="page__title">
  <%= title "Espaces" %>
  <% if can? :manage, MeetingRoom %>
  <div class="pull-right">
    <%= link_to 'Ajouter un espace', new_meeting_room_path, class: 'btn btn-info' %>
  </div>
  <% end %>
</h2>

<div class="panel col-xs-12">

  <div class="tablist-heading">
    <ul class="tablist">
      <%= nav_link "Tous", meeting_rooms_path %>
      <% if can? :manage, Floor %>
        <%= nav_link "Corbeille", deleted_meeting_rooms_path %>
      <% end %>
    </ul>
  </div>

  <div class="panel-body">
    <%= render 'list' %>
  </div>
</div>

app/views/meeting_rooms/edit.html.erb
<div class="row">
  <%= render 'form', meeting_room: @meeting_room %>
</div>

app/views/meeting_rooms/index.html.erb
<h2 class="page__title">
  <%= title "Espaces" %>
  <% if can? :manage, MeetingRoom %>
  <div class="pull-right">
    <%= link_to 'Ajouter un espace', new_meeting_room_path, class: 'btn btn-info' %>
  </div>
  <% end %>
</h2>

<div class="panel col-xs-12">

  <div class="tablist-heading">
    <ul class="tablist">
      <%= nav_link "Tous", meeting_rooms_path %>
      <% if can? :manage, Floor %>
        <%= nav_link "Corbeille", deleted_meeting_rooms_path %>
      <% end %>
    </ul>
  </div>

  <div class="panel-body">
    <%= render 'list' %>
  </div>
</div>

app/views/meeting_rooms/new.html.erb
<div class="row">
  <%= render 'form', meeting_room: @meeting_room %>
</div>

app/views/meeting_rooms/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-4">

    <!-- TODO: partial + finish -->
    <div class="panel-top">
      <div class="reservation-infos" style="background-color: <%= @meeting_room.colour %>">
        <div class="reservation-infos-content">
          <div class="reservation-infos-name">
            <%= @meeting_room.name %>
          </div>
          <div class="reservation-infos-floor">
            <%= @meeting_room.floor.present? ? @meeting_room.floor.name : "N/A" %> - <%= @meeting_room.capacity %> <%= 'place'.pluralize(@meeting_room.capacity) %>
          </div>
        </div>
        <div class="reservation-infos-bottom"></div>
      </div>
    </div>

    <div class="panel txt-c">
      <div class="panel-heading">
        <div class="thumbnail losange-thumb no-thumb place-thumb mb" style="width:68px;height:68px;"></div>

        <h2><%= @meeting_room.name %></h2>
      </div>

      <div class="panel-body">
        <% if can? :manage, MeetingRoom %>
          <%= link_to edit_meeting_room_path(@meeting_room), class: 'btn btn-default btn-icon' do %>
            <i class="material-icons">settings</i><span>Paramètres</span>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
  <div class="col-xs-12 col-md-8">
    <div class="panel">
      <div class="panel-heading">
        <h2>Liste des réservations</h2>
      </div>
      <div class="panel-body"></div>

    </div>
  </div>
</div>