config/routes.rb
Rails.application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'home#letsencrypt'

  root to: "home#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :events do
    get 'deleted' => "events#deleted", on: :collection
    get 'past' => "events#past", on: :collection
    get 'future' => "events#future", on: :collection
    match 'recover', to: 'events#recover', on: :member, via: [:put, :patch]
  end

  resources :companies do
    get 'deleted' => 'companies#deleted', on: :collection
    match 'recover', to: 'companies#recover', on: :member, via: [:put, :patch]
  end

  resources :programs do
    resources :seasons do
      get 'deleted' => 'seasons#deleted', on: :collection
      match 'recover', to: 'seasons#recover', on: :member, via: [:put, :patch]
    end
    get 'deleted' => 'programs#deleted', on: :collection
    match 'recover', to: 'programs#recover', on: :member, via: [:put, :patch]
  end

  resources :projects do
    get 'deleted' => 'projects#deleted', on: :collection
    match 'recover', to: 'projects#recover', on: :member, via: [:put, :patch]
    resources :members, only: [:create], controller: :project_members
    resources :logs, only: [:index, :create, :destroy], controller: :logs
  end

  resources :roles, only: [:destroy]

  resources :floors do
    get 'deleted' => 'floors#deleted', on: :collection
    match 'recover', to: 'floors#recover', on: :member, via: [:put, :patch]
  end

  resources :meeting_rooms do
    get 'deleted' => 'meeting_rooms#deleted', on: :collection
    match 'recover', to: 'meeting_rooms#recover', on: :member, via: [:put, :patch]
  end

  resources :reservations, except: [:show] do
    get 'past' => "reservations#past", on: :collection
    get 'deleted' => "reservations#deleted", on: :collection
    match 'recover', to: 'reservations#recover', on: :member, via: [:put, :patch]
    get 'search' => "reservations#search", on: :collection
  end

  resources :residents, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  namespace :api, defaults: {format: :json} do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      scope :events do
        get '/' => 'events#index'
        get 'today' => 'events#today'
        get 'public' => 'events#public'
      end
      scope :residents do
        get '/' => 'residents#index'
        get 'last' => 'residents#last'
      end
      scope :companies do
        get '/' => 'companies#index'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :seasons, dependent: :destroy
  has_many :roles, as: :entity, dependent: :destroy
  has_many :users, through: :roles
  belongs_to :floor

  has_attached_file :image, styles: { large: "1200x1200", medium: "300x300>", cover: "500x500>", thumb: "192x192>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  acts_as_paranoid
  audited

  def projects
    projects = []
    self.seasons.each do |season|
      projects.concat season.projects
    end
    projects
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy, :recover]

  load_and_authorize_resource except: [:index]

  # GET /programs
  # GET /programs.json
  def index
    authorize! :manage, Program
    @programs = Program.all.order(name: :asc)
  end

  # GET /programs/deleted
  def deleted
    @programs = Program.only_deleted
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @programs = Program.all.order(name: :asc)
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to programs_path, notice: I18n.t('programs.create') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to programs_path, notice: I18n.t('programs.update') }
      else
        format.html { render :edit }
      end
    end
  end

  # PATCH /programs/1/recover
  def recover
    @program.recover
    respond_to do |format|
      format.html { redirect_to programs_path, notice: I18n.t('programs.recover') }
      format.json { head :success }
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: I18n.t('programs.destroy') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :description, :floor_id, :image)
    end
  end

app/views/programs/_form.html.erb
<%= simple_form_for(@program) do |f| %>
  <%= f.error_notification %>

<div class="col-xs-12 col-md-8">
  <div class="panel">
    <div class="panel-heading">
      <% if f.object.new_record? %>
        <h2><%= title "Ajouter un programme" %></h2>
      <% else %>
        <h2><%= title "Modifier un programme" %></h2>
      <% end %>
    </div>

    <div class="panel-body">

      <div class="row form-row">

        <div class="form-group col-xs-12 align-items-center">
          <%= render "layouts/thumbnail", thumb: @program.image, size: "6rem", shape: "square-thumb", addclass: "pull-left mr" %>

          <%= f.file_field :image, as: :file, class: "inputfile", data: { :caption => "{nb} fichiers selectionnés" } %>
          <%= f.label :image, '<span class="label-btn">Envoyer une photo</span><span class="label-filename">Pas de fichier selectionné</span>'.html_safe %>
        </div>

      </div>

      <div class="row form-row">

        <div class="form-group col-md-6 has-feedback has-feedback-left">
          <%= f.label :name, "Nom du programme", class: "sr-only" %>
          <%= f.text_field :name, autofocus: true, placeholder: "Nom du programme", class: "form-control" %>
          <i class="form-control-feedback material-icons">location_city</i>
        </div>

        <div class="form-group select-wrapper  col-md-6 has-feedback has-feedback-left">
          <%= f.label :floor_id, "Étage", class: "sr-only" %>
          <%= f.association :floor, collection: Floor.order('number ASC'), class: 'form-control', label: false, prompt: "Étage" %>
          <i class="form-control-feedback material-icons">view_agenda</i>
        </div>

        <div class="form-group col-xs-12">
          <%= f.input :description, :input_html => { :rows => 4 } %>
        </div>

      </div>

    </div>

  </div>
</div>

<div class="col-xs-12 col-md-4">
  <div class="panel">
    <div class="panel-heading">
      <h3>Publier</h3>
    </div>
    <div class="panel-body">
      <ul class="simple-list muted">
        <% if @program.created_at.present? %>
          <li>
            <% if @program.audits.present? %>
              <% user_id = @program.audits.first.user.id %>
              <%= 'Créé il y a ' + time_ago_in_words(@program.created_at) + ' par ' %>
              <%= link_to @program.audits.first.user.name, resident_path(user_id) %>.
            <% else %>
              <%= 'Créé il y a ' + time_ago_in_words(@program.created_at) + '.' %>
            <% end %>
          </li>
        <% end %>
        <% if @program.updated_at != @program.created_at %>
          <li>
            <% if @program.audits.present? %>
            <%-# Évènement créés avec Audited -%>
              <% user_id = @program.audits.last.user.id %>
              <%= 'Modifié il y a ' + time_ago_in_words(@program.updated_at) + ' par ' %>
              <%= link_to @program.audits.last.user.name, resident_path(user_id) %>.
            <% else %>
            <%-# Évènement créés avant Audited -%>
              <%= 'Modifié il y a ' + time_ago_in_words(@program.updated_at) + '.' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="panel-footer">
      <% if f.object.new_record? %>
        <div class="flex-end">
          <%= f.submit "Publier", class: "btn btn-primary" %>
        </div>
      <% else %>
        <div class="space-between">
          <%= link_to "Supprimer", program_path(program), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "btn btn-link btn-link--danger" %>
          <%= f.submit "Sauvegarder", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% end %>

app/views/programs/_list.html.erb
<table class="table table-hover datatable">
  <thead>
    <tr>
      <th>Nom</th>
      <th data-orderable="false"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.name %></td>
        <td>
          <div class="pull-right">
            <% if current_page?(action: 'index') %>
              <%= link_to program_path(program), class: 'btn btn-default btn-xs' do %>
              <i class="material-icons">visibility</i><span>Voir</span>
              <% end %>
              <%= link_to edit_program_path(program), class: 'btn btn-default btn-xs' do %>
              <i class="material-icons">edit</i><span>Modifier</span>
              <% end %>
            <% end %>
            <% if current_page?(action: 'deleted') %>
              <%= link_to recover_program_path(program), method: :put, class: 'btn btn-success btn-xs' do %>
              <i class="material-icons">restore</i><span>Rétablir</span>
              <% end %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/programs/deleted.html.erb
<h2 class="page__title">
  <%= title "Programmes" %>
  <% if can? :manage, Program %>
    <div class="pull-right">
      <%= link_to 'Nouveau programme', new_program_path, class: 'btn btn-info' %>
    </div>
  <% end %>
</h2>

<div class="panel col-xs-12">
  <div class="tablist-heading">
    <ul class="tablist">
      <%= nav_link "Tous", programs_path %>
      <% if can? :manage, Project %>
        <%= nav_link "Corbeille", deleted_programs_path %>
      <% end %>
    </ul>
  </div>

  <div class="panel-body">
    <%= render 'list' %>
  </div>
</div>

app/views/programs/edit.html.erb
<div class="row">
  <%= render 'form', program: @program %>
</div>

app/views/programs/index.html.erb
<h2 class="page__title">
  <%= title "Programmes" %>
  <% if can? :manage, Program %>
    <div class="pull-right">
      <%= link_to 'Nouveau programme', new_program_path, class: 'btn btn-info' %>
    </div>
  <% end %>
</h2>

<div class="panel col-xs-12" id="list-items">
  <div class="tablist-heading">
    <ul class="tablist">
      <%= nav_link "Tous", programs_path %>
      <% if can? :manage, Project %>
        <%= nav_link "Corbeille", deleted_programs_path %>
      <% end %>
    </ul>

    <ul class="tablist right">
      <%= render "layouts/tablist-search" %>
    </ul>
  </div>

  <div class="panel-body row">

    <ul class="list list-items">
      <% @programs.each do |program| %>

        <li class="col-xs-12 col-md-6">
          <%= render "layouts/list-item", item: program %>
        </li>

      <% end %>
    </ul>

  </div>

</div>

app/views/programs/new.html.erb
<div class="row">
  <%= render 'form', program: @program %>
</div>

app/views/programs/show.html.erb
<%= render "projects/page-title" %>

<div class="panel col-xs-12" id="list-items">

  <%= render "projects/tablist" %>

  <div class="panel-body row">
    <ul class="list list-items">

      <% if @program.projects.each do |project| %>
        <li class="col-xs-12 col-md-4">
          <%= render 'projects/project-item', item: project %>
        </li>
      <% end.empty? %>
        <li class="col-xs-12">
          <p class="muted">Il n'y a pas de projets dans ce programme.</p>
        </li>
      <% end %>

    </ul>
  </div>

</div>