config/routes.rb
Rails.application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'home#letsencrypt'

  root to: "home#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :events do
    get 'deleted' => "events#deleted", on: :collection
    get 'past' => "events#past", on: :collection
    get 'future' => "events#future", on: :collection
    match 'recover', to: 'events#recover', on: :member, via: [:put, :patch]
  end

  resources :companies do
    get 'deleted' => 'companies#deleted', on: :collection
    match 'recover', to: 'companies#recover', on: :member, via: [:put, :patch]
  end

  resources :programs do
    resources :seasons do
      get 'deleted' => 'seasons#deleted', on: :collection
      match 'recover', to: 'seasons#recover', on: :member, via: [:put, :patch]
    end
    get 'deleted' => 'programs#deleted', on: :collection
    match 'recover', to: 'programs#recover', on: :member, via: [:put, :patch]
  end

  resources :projects do
    get 'deleted' => 'projects#deleted', on: :collection
    match 'recover', to: 'projects#recover', on: :member, via: [:put, :patch]
    resources :members, only: [:create], controller: :project_members
    resources :logs, only: [:index, :create, :destroy], controller: :logs
  end

  resources :roles, only: [:destroy]

  resources :floors do
    get 'deleted' => 'floors#deleted', on: :collection
    match 'recover', to: 'floors#recover', on: :member, via: [:put, :patch]
  end

  resources :meeting_rooms do
    get 'deleted' => 'meeting_rooms#deleted', on: :collection
    match 'recover', to: 'meeting_rooms#recover', on: :member, via: [:put, :patch]
  end

  resources :reservations, except: [:show] do
    get 'past' => "reservations#past", on: :collection
    get 'deleted' => "reservations#deleted", on: :collection
    match 'recover', to: 'reservations#recover', on: :member, via: [:put, :patch]
    get 'search' => "reservations#search", on: :collection
  end

  resources :residents, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  namespace :api, defaults: {format: :json} do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      scope :events do
        get '/' => 'events#index'
        get 'today' => 'events#today'
        get 'public' => 'events#public'
      end
      scope :residents do
        get '/' => 'residents#index'
        get 'last' => 'residents#last'
      end
      scope :companies do
        get '/' => 'companies#index'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :roles, as: :entity, dependent: :destroy
  has_many :users, through: :roles

  has_attached_file :image, styles: { large: "1200x1200", medium: "300x300>", cover: "500x500>" , thumb: "192x192>" }, default_url: "/images/:style/missing-image.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :season

  has_many :logs

  acts_as_paranoid
  audited

  # Project type can only be innovation project or startup
  validates :project_type, inclusion: { in: %w(innovation-project startup),
    message: "%{value} is not a valid type" }

  # Instance Methods
  def program
    self.season.program
  end

  def full_name
    self.name + ' (' + self.season.name + ' - ' + self.program.name + ')'
  end

  # Class Methods
  def self.types_collection
    [
      ["Projet d'innovation", "innovation-project"],
      ["Startup", "startup"]
    ]
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :recover]

  load_and_authorize_resource except: [:index]

  # GET /projects
  # GET /projects.json
  def index
    @programs = Program.all.order(name: :asc)
    authorize! :read, Project
    if current_user.role == "admin"
      @projects = Project.all
    else
      @projects = current_user.projects
    end
  end

  # GET /projects/deleted
  def deleted
    @programs = Program.all.order(name: :asc)
    @projects = Project.only_deleted
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @other_users = User.all - @project.users
    @logs = Log.where("project_id = ?", params[:id]).order('date DESC')
  end

  # GET /projects/new
  def new
    @project = Project.new
    @types_collection = Project.types_collection
    @seasons_collection = Season.collection_for_select
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: I18n.t('projects.create') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: I18n.t('projects.update') }
      else
        format.html { render :edit }
      end
    end
  end

  # PATCH /projects/1/recover
  def recover
    @project.recover
    respond_to do |format|
      format.html { redirect_to projects_path, notice: I18n.t('projects.recover') }
      format.json { head :success }
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: I18n.t('projects.destroy') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.with_deleted.find(params[:id])
      @types_collection = Project.types_collection
      @seasons_collection = Season.collection_for_select
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :project_type, :season_id, :description, :image)
    end
  end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

<div class="col-xs-12 col-md-8">
  <div class="panel">
    <div class="panel-heading">
      <% if f.object.new_record? %>
        <h2><%= title "Ajouter un projet" %></h2>
      <% else %>
        <h2><%= title "Modifier un projet" %></h2>
      <% end %>
    </div>

    <div class="panel-body">

      <div class="row form-row">

        <div class="form-group col-xs-12 align-items-center">
          <%= render "layouts/thumbnail", thumb: @project.image, size: "6rem", shape: "square-thumb", addclass: "pull-left mr" %>

          <%= f.file_field :image, as: :file, class: "inputfile", data: { :caption => "{nb} fichiers selectionnés" } %>
          <%= f.label :image, '<span class="label-btn">Envoyer une photo</span><span class="label-filename">Pas de fichier selectionné</span>'.html_safe %>
        </div>

      </div>

      <div class="row form-row">

        <div class="form-group col-md-12 has-feedback has-feedback-left">
          <%= f.label :name, "Nom du projet", class: "sr-only" %>
          <%= f.text_field :name, autofocus: true, placeholder: "Nom du projet", class: "form-control" %>
          <i class="form-control-feedback material-icons">assignment</i>
        </div>

        <div class="form-group select-wrapper col-md-6 has-feedback has-feedback-left">
          <%= f.label :project_type, "Type de projet", class: "sr-only" %>
          <%= f.input :project_type, as: :select, collection: @types_collection, label: false, class: "form-control" %>
          <i class="form-control-feedback material-icons">filter_list</i>
        </div>

        <div class="form-group select-wrapper col-md-6 has-feedback has-feedback-left">
          <%= f.label :season, "Saison", class: "sr-only" %>
          <%= f.association :season, label: false, collection: @seasons_collection, class: "form-control" %>
          <i class="form-control-feedback material-icons">date_range</i>
        </div>

        <div class="form-group col-xs-12">
          <%= f.input :description, :input_html => { :rows => 4 } %>
        </div>

      </div>

    </div>

  </div>
</div>

<div class="col-xs-12 col-md-4">
  <div class="panel">
    <div class="panel-heading">
      <h3>Publier</h3>
    </div>
    <div class="panel-body">
      <ul class="simple-list muted">
        <% if @project.created_at.present? %>
          <li>
            <% if @project.audits.present? %>
              <% user_id = @project.audits.first.user.id %>
              <%= 'Créé il y a ' + time_ago_in_words(@project.created_at) + ' par ' %>
              <%= link_to @project.audits.first.user.name, resident_path(user_id) %>.
            <% else %>
              <%= 'Créé il y a ' + time_ago_in_words(@project.created_at) + '.' %>
            <% end %>
          </li>
        <% end %>
        <% if @project.updated_at != @project.created_at %>
          <li>
            <% if @project.audits.present? %>
            <%-# Évènement créés avec Audited -%>
              <% user_id = @project.audits.last.user.id %>
              <%= 'Modifié il y a ' + time_ago_in_words(@project.updated_at) + ' par ' %>
              <%= link_to @project.audits.last.user.name, resident_path(user_id) %>.
            <% else %>
            <%-# Évènement créés avant Audited -%>
              <%= 'Modifié il y a ' + time_ago_in_words(@project.updated_at) + '.' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="panel-footer">
      <% if f.object.new_record? %>
        <div class="flex-end">
          <%= f.submit "Publier", class: "btn btn-primary" %>
        </div>
      <% else %>
        <div class="space-between">
          <%= link_to "Supprimer", project_path(project), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "btn btn-link btn-link--danger" %>
          <%= f.submit "Sauvegarder", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% end %>

app/views/projects/_list.html.erb
<table class="table table-hover datatable">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Programme</th>
      <th>Saison</th>
      <th data-orderable="false"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.season.present? ? project.program.name : "N/A" %></td>
        <td><%= project.season.present? ? project.season.name : "N/A" %></td>
        <td>
          <div class="pull-right">
            <% if current_page?(action: 'index') %>
              <%= link_to project_path(project), class: 'btn btn-default btn-xs' do %>
              <i class="material-icons">visibility</i><span>Voir</span>
              <% end %>
              <%= link_to edit_project_path(project), class: 'btn btn-default btn-xs' do %>
              <i class="material-icons">edit</i><span>Modifier</span>
              <% end %>
            <% end %>
            <% if current_page?(action: 'deleted') %>
              <%= link_to recover_project_path(project), method: :put, class: 'btn btn-success btn-xs' do %>
              <i class="material-icons">restore</i><span>Rétablir</span>
              <% end %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/_member-avatars.html.erb
<div class="member-avatars">

  <% members = [] %>

  <% item.roles.where(name: ["director", "coach", "mentor"]).each do |role| %>
    <% members.push(role) %>
  <% end %>

  <% item.roles.where(name: "client").each do |role| %>
    <% members.push(role) %>
  <% end %>

  <% item.roles.where(name: ["member"]).each do |role| %>
    <% members.push(role) %>
  <% end %>

  <% if members.count > 5 %>

    <% members.first(4).each do |member| %>
      <span data-toggle="tooltip" data-placement="top" title="<%= member.user.name %>">
        <%= render "layouts/thumbnail", thumb: member.user.photo %>
      </span>
    <% end %>

    <div class="member-more">
      <div class="member-more__thumb">+<%= members.count - 4 %></div>
      <div class="member-more__tooltip top">
        <ul class="member-more__list">
          <% members[4..-1].each do |member| %>
            <li><%= member.user.name %></li>
          <% end %>
        </ul>
      </div>
    </div>

  <% elsif members.count <= 5 %>

    <% members.each do |member| %>
      <span data-toggle="tooltip" data-placement="top" title="<%= member.user.name %>">
        <%= render "layouts/thumbnail", thumb: member.user.photo %>
      </span>
    <% end %>

  <% elsif members.count = 0 %>

    Aucun participants...

  <% end %>

</div>

app/views/projects/_page-title.html.erb
<h2 class="page__title">
  <% if can? :manage, Project %>
    <%= title "Projets" %>
    <div class="pull-right">
      <% if @program.presence %>
        <%= link_to 'Nouvelle saison', new_program_season_path(@program), class: 'btn btn-default' %>
      <% end %>
      <%= link_to 'Nouveau projet', new_project_path, class: 'btn btn-info' %>
    </div>
  <% else %>
    <%= title "Mes projets" %>
  <% end %>
</h2>

app/views/projects/_project-item.html.erb
<div class="project-item">
  <div class="project-item__container">
    <div class="project-item__header">
      <div class="project-item__cover embed-responsive-16by9">
        <%= image_tag item.image.url(:cover) %>
      </div>
      <div class="project-item__overlay">
        <%= render "projects/member-avatars", item: item %>
      </div>
    </div>
    <div class="project-item__content">
      <!-- <div class="project-item__date">
        Dates
      </div> -->
      <h3 class="project-item__title">
        <%= link_to item.name, project_path(item), class: "name" %>
        <% if can? :manage, Project %>
          <span class="project-item__actions muted">
            <%= link_to "Modifier", edit_project_path(item) %>
          </span>
        <% end %>
      </h3>
      <div class="project-item__subtitle">
        <% @participants = item.roles.count.to_s %>
        <%= @participants  + ' participant'.pluralize(@participants) %> -
        <% @logs = item.logs.count.to_s %>
        <%= @logs + ' actualité'.pluralize(@logs) %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_tablist.html.erb
<div class="tablist-heading">
  <ul class="tablist">
    <%= nav_link "Tous", projects_path %>
    <% @programs.each do |program| %>
      <%= nav_link program.name, program_path(program) %>
    <% end %>
    <% if can? :manage, Project %>
      <%= nav_link "Corbeille", deleted_projects_path %>
    <% end %>
  </ul>

  <ul class="tablist right">
    <%= render "layouts/tablist-search" %>
  </ul>
</div>

app/views/projects/deleted.html.erb
<%= render "projects/page-title" %>

<div class="panel col-xs-12">

  <%= render "projects/tablist" %>

  <div class="panel-body">
    <%= render 'list' %>
  </div>

</div>

app/views/projects/edit.html.erb
<div class="row">
  <%= render 'form', project: @project, season_collection: @season_collection %>
</div>

app/views/projects/index.html.erb
<%= render "projects/page-title" %>

<div class="panel col-xs-12" id="list-items">

  <%= render "projects/tablist" %>

  <div class="panel-body row">

    <ul class="list list-items">
      <% if @projects.each do |project| %>
        <li class="col-xs-12 col-md-4">
          <%= render 'projects/project-item', item: project %>
        </li>
      <% end.empty? %>
        <li class="col-xs-12">
          <p class="muted">Il n'y a pas de projets dans ce programme.</p>
        </li>
      <% end %>
    </ul>
    <ul class="list list-items">

  </div>

</div>

app/views/projects/logs.html.erb
<%= render "projects/show/page-title" %>

<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= render "layouts/card-item", item: @project %>
  </div>

  <div class="col-xs-12 col-md-8">
    <div class="panel">
      <div class="tablist-heading">
        <%= render "projects/show/tablist" %>

        <ul class="tablist right">
          <% if can? :manage, Log %>
            <li><a href="#" data-toggle="modal" data-target="#newLogModal" class="tablist-action">Ajouter</a></li>
          <% end %>
        </ul>
      </div>


      <% if @logs.each do |log| %>

        <%= render "projects/logs/log-item", item: log %>

      <% end.empty? %>

        <div class="panel-body">
          <p class="muted">Il n'y a aucun historique pour ce projet.</p>
        </div>

      <% end %>
    </div>
  </div>
</div>

<%= render "projects/logs/log-modal" %>

app/views/projects/new.html.erb
<div class="row">
  <%= render 'form', project: @project, season_collection: @season_collection %>
</div>

app/views/projects/show.html.erb
<%= render "projects/show/page-title" %>

<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= render "layouts/card-item", item: @project %>
  </div>

  <div class="col-xs-12 col-md-8">
    <div class="panel">
      <div class="tablist-heading">
        <%= render "projects/show/tablist" %>

        <ul class="tablist right">
          <% if can? :manage, Role %>
            <li><a href="#" data-toggle="modal" data-target="#newMemberModal" class="tablist-action">Ajouter un membre</a></li>
          <% end %>
        </ul>
      </div>

      <div class="panel-body">

        <% if @project.roles.where(name: ["coach", "mentor", "director"]).present? %>
          <div class="panel-section">
            <h3 class="panel-section__title">Équipe Schoolab</h3>
            <div class="row">
              <% @project.roles.where(name: ["coach", "mentor", "director"]).each do |role| %>
                <div class="col-xs-12 col-md-6">
                  <%= render "projects/show/member-item", role: role %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if @project.roles.where(name: "client").present? %>
          <div class="panel-section">
            <h3 class="panel-section__title">Équipe du client</h3>
            <div class="row">
              <% @project.roles.where(name: "client").each do |role| %>
                <div class="col-xs-12 col-md-6">
                  <%= render "projects/show/member-item", role: role %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if @project.roles.where(name: "member").present? %>
          <div class="panel-section">
            <h3 class="panel-section__title">Équipe du projet</h3>
            <div class="row">
              <% @project.roles.where(name: "member").each do |role| %>
                <div class="col-xs-12 col-md-6">
                  <%= render "projects/show/member-item", role: role %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

<%= render "projects/show/member-modal" %>