config/routes.rb
Rails.application.routes.draw do

  get '/.well-known/acme-challenge/:id' => 'home#letsencrypt'

  root to: "home#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :events do
    get 'deleted' => "events#deleted", on: :collection
    get 'past' => "events#past", on: :collection
    get 'future' => "events#future", on: :collection
    match 'recover', to: 'events#recover', on: :member, via: [:put, :patch]
  end

  resources :companies do
    get 'deleted' => 'companies#deleted', on: :collection
    match 'recover', to: 'companies#recover', on: :member, via: [:put, :patch]
  end

  resources :programs do
    resources :seasons do
      get 'deleted' => 'seasons#deleted', on: :collection
      match 'recover', to: 'seasons#recover', on: :member, via: [:put, :patch]
    end
    get 'deleted' => 'programs#deleted', on: :collection
    match 'recover', to: 'programs#recover', on: :member, via: [:put, :patch]
  end

  resources :projects do
    get 'deleted' => 'projects#deleted', on: :collection
    match 'recover', to: 'projects#recover', on: :member, via: [:put, :patch]
    resources :members, only: [:create], controller: :project_members
    resources :logs, only: [:index, :create, :destroy], controller: :logs
  end

  resources :roles, only: [:destroy]

  resources :floors do
    get 'deleted' => 'floors#deleted', on: :collection
    match 'recover', to: 'floors#recover', on: :member, via: [:put, :patch]
  end

  resources :meeting_rooms do
    get 'deleted' => 'meeting_rooms#deleted', on: :collection
    match 'recover', to: 'meeting_rooms#recover', on: :member, via: [:put, :patch]
  end

  resources :reservations, except: [:show] do
    get 'past' => "reservations#past", on: :collection
    get 'deleted' => "reservations#deleted", on: :collection
    match 'recover', to: 'reservations#recover', on: :member, via: [:put, :patch]
    get 'search' => "reservations#search", on: :collection
  end

  resources :residents, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  namespace :api, defaults: {format: :json} do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      scope :events do
        get '/' => 'events#index'
        get 'today' => 'events#today'
        get 'public' => 'events#public'
      end
      scope :residents do
        get '/' => 'residents#index'
        get 'last' => 'residents#last'
      end
      scope :companies do
        get '/' => 'companies#index'
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :floor
  has_many :users

  has_attached_file :image, styles: { large: "1200x1200", medium: "300x300>", cover: "500x500>", thumb: "192x192>" }, default_url: "/images/:style/missing-company.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  acts_as_paranoid
  audited

  def employees
    return User.where('company_id = ?', self.id)
  end

end

app/controllers/api/companies_controller.rb
class Api::CompaniesController < Api::BaseController
  before_action :authenticate_user!

  # GET /companies.json
  def index
    @companies = Company.all
    authorize! :read, Company
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :recover]

  load_and_authorize_resource

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.order(name: :asc)
  end

  # GET /companies/deleted
  def deleted
    @companies = Company.only_deleted.order(name: :asc)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @employees = User.where("company_id = ?", params[:id]).order(:first_name)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_path, notice: I18n.t('companies.create') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to companies_path, notice: I18n.t('companies.update') }
      else
        format.html { render :edit }
      end
    end
  end

  # PATCH /companies/1/recover
  def recover
    @company.recover
    respond_to do |format|
      format.html { redirect_to companies_path, notice: I18n.t('companies.recover') }
      format.json { head :success }
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: I18n.t('companies.destroy') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :floor_id, :image, :description, :phone, :email)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>

<div class="col-xs-12">
  <h2 class="page__title">
    <% if f.object.new_record? %>
      <%= title "Ajouter une entreprise" %>
    <% else %>
      <%= title "Modifier une entreprise" %>
    <% end %>
  </h2>
</div>

<div class="col-xs-12 col-md-8">
  <div class="panel">
    <div class="panel-heading">
      <h3>Informations générales</h3>
    </div>
    <div class="panel-body">
      <div class="row form-row">

        <div class="form-group col-xs-12 align-items-center">
          <%= render "layouts/thumbnail", thumb: @company.image, size: "6rem", addclass: "mr" %>

          <%= f.file_field :image, as: :file, class: "inputfile", data: { :caption => "{nb} fichiers selectionnés" } %>
          <%= f.label :image, '<span class="label-btn">Envoyer une photo</span><span class="label-filename">Pas de fichier selectionné</span>'.html_safe %>
        </div>

      </div>
      <div class="row form-row">

        <div class="form-group col-md-6 has-feedback has-feedback-left">
          <%= f.label :name, "Nom de l'entreprise", class: "sr-only" %>
          <%= f.text_field :name, autofocus: true, placeholder: "Nom de l'entreprise", class: "form-control" %>
          <i class="form-control-feedback material-icons">location_city</i>
        </div>

        <div class="form-group select-wrapper col-md-6 has-feedback has-feedback-left">
          <%= f.label :floor, "Étage", class: "sr-only" %>
          <%= f.association :floor, class: 'form-control', label: false, prompt: "Étage" %>
          <i class="form-control-feedback material-icons">view_agenda</i>
        </div>

        <div class="form-group col-xs-12">
          <%= f.input :description, :input_html => { :rows => 4 } %>
        </div>

        <div class="form-group col-md-6 has-feedback has-feedback-left">
          <%= f.label :email, "Email de contact", class: "sr-only" %>
          <%= f.text_field :email, placeholder: "Email de contact", class: "form-control" %>
          <i class="form-control-feedback material-icons">email</i>
        </div>

        <div class="form-group col-md-6 has-feedback has-feedback-left">
          <%= f.label :phone, "Numéro de téléphone", class: "sr-only" %>
          <%= f.text_field :phone, placeholder: "Numéro de téléphone", class: "form-control" %>
          <i class="form-control-feedback material-icons">phone</i>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="col-xs-12 col-md-4">
  <div class="panel">
    <div class="panel-heading">
      <h3>Publier</h3>
    </div>
    <div class="panel-body">
      <ul class="simple-list muted">
        <% if @company.created_at.present? %>
          <li>
            <% if @company.audits.present? %>
              <% user_id = @company.audits.first.user.id %>
              <%= 'Créé il y a ' + time_ago_in_words(@company.created_at) + ' par ' %>
              <%= link_to @company.audits.first.user.name, resident_path(user_id) %>.
            <% else %>
              <%= 'Créé il y a ' + time_ago_in_words(@company.created_at) + '.' %>
            <% end %>
          </li>
        <% end %>
        <% if @company.updated_at != @company.created_at %>
          <li>
            <% if @company.audits.present? %>
            <%-# Évènement créés avec Audited -%>
              <% user_id = @company.audits.last.user.id %>
              <%= 'Modifié il y a ' + time_ago_in_words(@company.updated_at) + ' par ' %>
              <%= link_to @company.audits.last.user.name, resident_path(user_id) %>.
            <% else %>
            <%-# Évènement créés avant Audited -%>
              <%= 'Modifié il y a ' + time_ago_in_words(@company.updated_at) + '.' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="panel-footer">
      <% if f.object.new_record? %>
        <div class="flex-end">
          <%= f.submit "Publier", class: "btn btn-primary" %>
        </div>
      <% else %>
        <div class="space-between">
          <%= link_to "Supprimer", company_path(company), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "btn btn-link btn-link--danger" %>
          <%= f.submit "Sauvegarder", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% end %>

app/views/companies/_list.html.erb
<table class="datatable table table-hover">
  <thead>
    <tr>
      <th>Nom</th>
      <th data-orderable="false"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td>
          <div class="pull-right">
            <% if current_page?(action: 'index') %>
              <%= link_to company_path(company), class: 'btn btn-default btn-xs' do %>
              <i class="material-icons">visibility</i><span>Voir</span>
              <% end %>
              <%= link_to edit_company_path(company), class: 'btn btn-default btn-xs' do %>
              <i class="material-icons">edit</i><span>Modifier</span>
              <% end %>
            <% end %>
            <% if current_page?(action: 'deleted') %>
              <%= link_to recover_company_path(company), method: :put, class: 'btn btn-success btn-xs' do %>
              <i class="material-icons">restore</i><span>Rétablir</span>
              <% end %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/deleted.html.erb
<h2 class="page__title">
  <%= title "Entreprises" %>
  <% if can? :manage, Company %>
    <div class="pull-right">
      <%= link_to 'Nouvelle entreprise', new_company_path, class: 'btn btn-info' %>
    </div>
  <% end %>
</h2>

<div class="panel col-xs-12">
  
  <div class="tablist-heading">
    <ul class="tablist">
      <%= nav_link "Tous", companies_path %>
      <%= nav_link "Corbeille", deleted_companies_path %>
    </ul>
  </div>

  <div class="panel-body">
    <%= render 'list' %>
  </div>

</div>

app/views/companies/edit.html.erb
<div class="row">
  <%= render 'form', company: @company %>
</div>

app/views/companies/index.html.erb
<h2 class="page__title">
  <%= title "Entreprises" %>
  <% if can? :manage, Company %>
    <div class="pull-right">
      <%= link_to 'Nouvelle entreprise', new_company_path, class: 'btn btn-info' %>
    </div>
  <% end %>
</h2>

<div class="panel col-xs-12">

  <div class="panel-body row">

    <%= render "list" %>

  </div>

</div>

app/views/companies/new.html.erb
<div class="row">
  <%= render 'form', company: @company %>
</div>

app/views/companies/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-4">
    <%= render "layouts/card-item", item: @company %>
  </div>

  <div class="col-xs-12 col-md-8">

    <div class="panel">
      <div class="panel-heading">
        <h2>Liste des employés</h2>
      </div>
      <div class="panel-body">
        <% if @employees.each do |employee| %>

          <%= render "layouts/list-item", item: employee %>

        <% end.empty? %>

          <p class="muted">Il n'y a personne dans cette entreprise...</p>

        <% end %>
      </div>
    </div>
  </div>
</div>